export 'package:data_layer/model/example_data/task.dart';

final Map<String, List<Map<String, dynamic>>> tasksByDate = {
  'Dec 1, 2024': [
    {
      'id': '1',
      'title': 'Cho gà ăn',
      'status': 'Đã làm',
      'location': 'Chuồng gà Trưởng Thành',
      'date': 'Dec 1, 2024',
    },
    {
      'id': '2',
      'title': 'Làm sạch chuồng',
      'status': 'Đã làm',
      'location': 'Chuồng gà Con',
      'date': 'Dec 1, 2024',
    },
    {
      'id': '3',
      'title': 'Kiểm tra sức khỏe gà',
      'status': 'Đã làm',
      'location': 'Chuồng gà Đông Tảo',
      'date': 'Dec 1, 2024',
    },
    {
      'id': '4',
      'title': 'Thu hoạch trứng',
      'status': 'Đã làm',
      'location': 'Chuồng gà Trưởng Thành',
      'date': 'Dec 1, 2024',
    },
  ],
  'Dec 2, 2024': [
    {
      'id': '5',
      'title': 'Cho gà ăn',
      'status': 'Đã làm',
      'location': 'Chuồng gà Con',
      'date': 'Dec 2, 2024',
    },
    {
      'id': '6',
      'title': 'Vệ sinh chuồng',
      'status': 'Đang làm',
      'location': 'Chuồng gà Đông Tảo',
      'date': 'Dec 2, 2024',
    },
    {
      'id': '7',
      'title': 'Tiêm vắc-xin',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Trưởng Thành',
      'date': 'Dec 2, 2024',
    },
    {
      'id': '8',
      'title': 'Kiểm tra sức khỏe gà',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Con',
      'date': 'Dec 2, 2024',
    },
  ],
  'Dec 3, 2024': [
    {
      'id': '9',
      'title': 'Cho gà ăn',
      'status': 'Đã làm',
      'location': 'Chuồng gà Đông Tảo',
      'date': 'Dec 3, 2024',
    },
    {
      'id': '10',
      'title': 'Làm sạch chuồng',
      'status': 'Đang làm',
      'location': 'Chuồng gà Trưởng Thành',
      'date': 'Dec 3, 2024',
    },
    {
      'id': '11',
      'title': 'Thu hoạch trứng',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Con',
      'date': 'Dec 3, 2024',
    },
    {
      'id': '12',
      'title': 'Kiểm tra sức khỏe gà',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Đông Tảo',
      'date': 'Dec 3, 2024',
    },
  ],
  'Dec 4, 2024': [
    {
      'id': '13',
      'title': 'Cho gà ăn',
      'status': 'Đã làm',
      'location': 'Chuồng gà Trưởng Thành',
      'date': 'Dec 4, 2024',
    },
    {
      'id': '14',
      'title': 'Vệ sinh chuồng',
      'status': 'Đang làm',
      'location': 'Chuồng gà Con',
      'date': 'Dec 4, 2024',
    },
    {
      'id': '15',
      'title': 'Tiêm vắc-xin',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Đông Tảo',
      'date': 'Dec 4, 2024',
    },
    {
      'id': '16',
      'title': 'Làm sạch chuồng',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Trưởng Thành',
      'date': 'Dec 4, 2024',
    },
  ],
  'Dec 5, 2024': [
    {
      'id': '17',
      'title': 'Cho gà ăn',
      'status': 'Đã làm',
      'location': 'Chuồng gà Con',
      'date': 'Dec 5, 2024',
    },
    {
      'id': '18',
      'title': 'Thu hoạch trứng',
      'status': 'Đang làm',
      'location': 'Chuồng gà Đông Tảo',
      'date': 'Dec 5, 2024',
    },
    {
      'id': '19',
      'title': 'Kiểm tra sức khỏe gà',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Trưởng Thành',
      'date': 'Dec 5, 2024',
    },
    {
      'id': '20',
      'title': 'Làm sạch chuồng',
      'status': 'Chưa làm',
      'location': 'Chuồng gà Con',
      'date': 'Dec 5, 2024',
    },
  ],
};
